package Simon;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

public class MainMenu extends JPanel { //classe contenant le menu principal
    private JPanel mainMenuPane;
    private BufferedImage image;
    /*private Toolkit toolkit = Toolkit.getDefaultToolkit();
    private Dimension dim = toolkit.getScreenSize();
    private int width = dim.width;
    private int height = dim.height;
    private double x;
    private double y;*/

    public MainMenu() {

        try {
            //System.out.println(new File(".").getPath());
            File file = new File("resources/simon.jpg").getAbsoluteFile();

//            FileOutputStream sortie = new FileOutputStream("test.txt");
//            sortie.write(150);
//            sortie.close();
//            FileInputStream entree = new FileInputStream("test.txt");
//            System.out.println("valeur entree: "+ entree.read());


            image = ImageIO.read(file);

            /* x = image.getWidth() / width;
            y = image.getHeight() /height;*/

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }


    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, null);

        //g.scale(x,y);
    }

    public JPanel getMainMenuPane() {
        return mainMenuPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainMenuPane = new JPanel();
        mainMenuPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainMenuPane;
    }
}

